
package soaps;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://soapS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soaps.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPersons", targetNamespace = "http://soapS/", className = "soaps.SearchPersons")
    @ResponseWrapper(localName = "searchPersonsResponse", targetNamespace = "http://soapS/", className = "soaps.SearchPersonsResponse")
    @Action(input = "http://soapS/PersonWebService/searchPersonsRequest", output = "http://soapS/PersonWebService/searchPersonsResponse")
    public List<Person> searchPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<soaps.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://soapS/", className = "soaps.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://soapS/", className = "soaps.GetPersonsResponse")
    @Action(input = "http://soapS/PersonWebService/getPersonsRequest", output = "http://soapS/PersonWebService/getPersonsResponse")
    public List<Person> getPersons();

}
